# TensorBoard logger configuration

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.output_dir}/tensorboard/"
  name: null
  version: null
  log_graph: false
  default_hp_metric: true
  prefix: ""
